---
- name: "Common configuration"
  hosts: "{{ hosts_group | default('all') }}"
  tasks:
    - name: "Update apt cache"
      ansible.builtin.apt:
        update_cache: true
        upgrade: true
      when: ansible_pkg_mgr == "apt"
    - name: Set timezone
      community.general.timezone:
        name: "{{ timezone }}"
      when: "timezone is defined and timezone | length > 0"
      become: true
